drop table T_WORK if exists;
CREATE TABLE T_WORK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE,
    DESCRIPTION VARCHAR(200),
    WIDTH INT,
    HEIGHT INT,
    PRICE DECIMAL(12,2),
    STOCK INT,
    URL VARCHAR(200)
);